== Notes

Quick notes / findings about manfredsteyer/angular-microfrontend.

{empty} +

==== Installation
`git clone` , `npm run build` , `npm start` does the job just fine.


{empty} +

==== How it works.

[options=header,cols="2,2,8"]
|===
| A | calls B | Comment
|main.ts | app/app.module |
|app.module | app.component |
| app.component | shell/shell.service.init(config) | Config is defined inline here. +
Paths to transpiled clients A-D are defined here. +
> e.g. `assets/micro-frontends/client-a/main.js`. +
Modifying `projects/client-a` indeed affects the app after a `npm run build` / `npm start` cycle. +
> Client A : Flight-Search +
> Client B : Passengers. +
> Client C-D : `.ts` files missing.
| init(config) | preloadClients() | if config.preload
| preloadClients | load |
|===


{empty} +

==== Conclusion
* Would be fun to see how an App can register itself, and it's authorisation server via a simple POST request.
    ** Then have the user log in, and show him a page, that links to all the "registered" Apps he has access to.








{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +


=== Web Components
Set of feature that provide a standard component model for the Web.

* encapsulation
* interoperability
* Custom Elements
* Shadow DOM
* HTML Templates

{empty} +

=== Glossary
|===
| linting | static checking source code via some program.
|===



=== Architectural Goals
|===
| Isolation
| Separate Deployment
| Single Page Shell
| Different SPA-Frameworks
| Tree Shaking
| Vendor Bundles
| Several MFEs at the same time
| Prevents Version Conflicts
| Spearate Development
| One optimized solution (bundle)
|===

{empty} +

=== Micro vs Macro Architecture
* Macro : between apps.
* Micro : within apps.

{empty} +


